[package]
name = "ecstatic"
version = "0.3.1"
authors = ["Nathan McKnight <@ntmck1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ecstatic_storage = { path = "../ecstatic_storage" }
